### PR TITLE
Bump Elixir to v1.12.3

### PR DESCRIPTION
**Pull request by sgerrand**
💁 These changes update the Elixir 1.12 version stream to 1.12.3.

### CODE REVIEW

**Comment by sgerrand** [comment]
👋 @getong, are you able to review this change?

**Comment by getong** [comment]
@sgerrand 
Would you rebase to one commit?

**Comment by sgerrand** [comment]
🙇 All done @getong.

**Comment by sgerrand** [comment]
Thank you! Are you able to run `generate-stackbrew-library.sh` to add this new version to https://github.com/docker-library/official-images/blob/master/library/elixir?

**Comment by getong** [comment]
docker-library/official-images#10872

**Pull request merged**
