### PR TITLE
Prettify GitHub Workflow config file

### PR DESCRIPTION
**Pull request by kianmeng**
Resolved via `prettier -w **/*.yaml`

### CODE REVIEW

**Comment by kianmeng** [comment]
@getong this is an old PR, let me know if anything else needed?

**Comment by getong** [comment]
I don't know, I don't care about it.
what kind of tool are you using?

**Comment by kianmeng** [comment]
> what kind of tool are you using?

https://github.com/prettier/prettier

**Comment by kianmeng** [comment]
:partying_face: :partying_face: :partying_face: :partying_face: :partying_face:

**Pull request merged**
