### PR TITLE
Add OTP25 support for v1.14

### PR DESCRIPTION
**Pull request by Kartstig**
- Adds OTP25 support for v1.14 images
- Relates to https://github.com/c0b/docker-elixir/pull/153

I pushed this to https://hub.docker.com/layers/kartstig/elixir/1.14.4-otp-25/images/sha256-46266b1d21b3533231a1e705027ef1aef29fcf6267e99544ab93c826d19ce31f?context=repo

Sorry about the confusion. I thought this wasn't the correct repo, but appears to be since the main repo isn't maintained anymore

### CODE REVIEW

**Comment by getong** [comment]
The 1.14  branch has erlang 25 support, why does it need a new directory ?

**Comment by Kartstig** [comment]
@getong Hmm I don't see that branch. Are you talking about this repository or a different fork?

image

**Comment by Kartstig** [comment]
oh you mean the `slim` and `alpine` folders

https://github.com/erlef/docker-elixir/blob/master/1.14/slim/Dockerfile

https://github.com/erlef/docker-elixir/blob/master/1.14/alpine/Dockerfile

**Comment by getong** [comment]
> oh you mean the `slim` and `alpine` folders
> 
> https://github.com/erlef/docker-elixir/blob/master/1.14/slim/Dockerfile
> 
> https://github.com/erlef/docker-elixir/blob/master/1.14/alpine/Dockerfile

yes

**Comment by Kartstig** [comment]
I'll close this as it's no longer needed

**Pull request closed without merging**
