### PR TITLE
Add Erlang/OTP 25 variants of Elixir 1.13 images

### PR DESCRIPTION
**Pull request by anmlnath**
I'm not exactly sure what the process is for updating the Erlang version. Is this okay?

#39

### CODE REVIEW

**Comment by idyll** [comment]
👍🏻

**Comment by getong** [comment]
would you rebase your commit into one commit?

**Comment by anmlnath** [comment]
@getong Yes, that's done. Thanks @getong

**Comment by getong** [comment]
docker-library/official-images#12545

**Pull request merged**
