### PR TITLE
Docker image for Elixir 1.13.4 and Erlang 23

### PR DESCRIPTION
**Pull request by tripathy-rakesh1**
Proposing Docker file for Elixir 1.13.4 and Erlang 23-slim

### CODE REVIEW

**Comment by duksis** [comment]
I assume this PR is aimed to close https://github.com/erlef/docker-elixir/issues/65

shouldn't this file be located in a folder `otp-23-slim` instead of just `otp-23`? 
if there is a `otp-23-slim` wouldn't it make sense to have `otp-23` and `otp-23-alpine` as well?

when introducing a new OTP version does it make sense to add tests for it as well? 
https://github.com/erlef/docker-elixir/blob/master/.github/workflows/elixir.yaml#L11

**Comment by getong** [comment]
generate-stackbrew-library.sh needs to add otp-23-slim.

**Comment by getong** [comment]
#67 #69 should be made into one pr, and rebase into one commit.

**Comment by getong** [comment]
Would you rebase into one commit?

**Comment by tripathy-rakesh1** [comment]
https://github.com/erlef/docker-elixir/pull/69 has been closed and no longer required, can we proceed further with one PR https://github.com/erlef/docker-elixir/pull/67 .

**Comment by getong** [comment]
I make docker-library/official-images#14527 , and this pr is merged.

**Pull request closed without merging**
